language: objective-c
osx_image: xcode9.3
script:
- xcrun xcodebuild -project BTree.xcodeproj -scheme BTree-macOS test
- xcrun xcodebuild -project BTree.xcodeproj -scheme BTree-iOS
- xcrun xcodebuild -project BTree.xcodeproj -scheme BTree-watchOS
- xcrun xcodebuild -project BTree.xcodeproj -scheme BTree-tvOS
- swift build
after_success: bash <(curl -s https://codecov.io/bash)
